
var GLOBALE_FUN=GLOBALE_FUN||{};$(function(){GLOBALE_FUN.getErrorWishlist=function(data){var errors={'notOwner':"Vous n'êtes pas propriétaire de l'objet.",'codicNotExists':"L'identifiant du produit est inconnu.",'wishlistNameExists':"Le nom de la liste est déjà utilisé.",'wishlistsCountOver':"Vous avez atteint le nombre maximum de listes, vous pouvez supprimer une liste pour en créer une nouvelle ou modifier une liste existante.",'wishlistIdNotExists':"L'identifiant de la liste d'envies est inconnu.",'missingOrBadParameter':"Un paramètre est manquant ou erroné.",'codicNotExistsInCatalog':"L'identifiant du produit est inconnu.",'wishlistProductsCountOver':"Vous avez atteint le nombre maximum de produits dans une liste, vous pouvez supprimer un produit de votre liste ou ajouter votre produit dans une nouvelle liste."}
if(data){return errors[data.errorCode]||'Erreur inconnue :'+data.errorMessage;}
return'Erreur inconnue';}
DARTY_CONF.CONST.CCD_USER=function(){var ccd=DARTY_CONF.CONST.DCOM_VERSION&&DARTY_CONF.getCookie("CK_BO_USER")!==null;if(ccd){document.documentElement.className=document.documentElement.className+" darty_com_ccd";}
return ccd;}();DARTY_CONF.isTrackingAuthorized=function(){return DARTY_CONF.CONST.DCOM_VERSION&&!DARTY_CONF.CONST.CCD_USER;}();});

var DARTY_CONF=DARTY_CONF||{};DARTY_CONF.CONST.SECURITY=DARTY_CONF.CONST.SECURITY||"";function modalAdd(config){var modal=$('#modal-add-product');var name=modal.find('#wishlist-new-name');var noteBloc=modal.find('.form-note');var note=noteBloc.find('#wishlist-new-note');var select=modal.find('#wishlist-select-name');var confidentiality=modal.find('[name="confidentiality"]');var submit=modal.find('[data-valid]');var prdPicture=modal.find('[data-picture]');var prdFamily=modal.find('[data-family]');var prdName=modal.find('[data-name]');var prdCopyInfos=modal.find('.product-copy-infos');if(!$('html').hasClass('ie8')){new Clipboard('[data-clipboard]');}
confidentiality.filter(':checked').parent().addClass('active');confidentiality.on('change',function(){modal.find('.field-radio-tab').removeClass('active');confidentiality.filter(':checked').parent().addClass('active');});$.get(DARTY_CONF.CONST.CTX_PATH+'nav/extra/ajax/wishlist?operation=add_product',function(data){select.html($(data).find('option'));select[0].selectedIndex=0;select.on('change',function(){submit.prop('disabled',false);});select.find('[value="'+config.wishlist+'"]').prop('disabled',true);});if(config.codics){prdCopyInfos.show();noteBloc.hide();}else{prdCopyInfos.hide();noteBloc.show();}
if(config.codics){$('#product-copy-number').text(config.codics.split(':').length);prdPicture.attr('src','');prdFamily.text('');prdName.text('');}else{prdPicture.attr('src',config.picture);prdFamily.text(config.family);prdName.text(config.name);}
name.val('');modal.find('.success').text('');DARTY_CONF.TRACKING.omniture_displayAddProductToWishlist();name.on('keyup',function(){var wishlistName=name.val();if((null!==wishlistName&&''!==$.trim(wishlistName))||(''!=select.val()&&null!=select.val())){submit.prop('disabled',false);}else{submit.prop('disabled',true);}});submit.on('click',function(){var self=$(this);var url='';var wishlistName=name.val();var wishlistId=select.val();var wishlistConfidentiality=confidentiality.filter(':checked').val();if(null!==wishlistName&&''!==$.trim(wishlistName)){url+=self.data('url-create');url+='?name='+encodeURIComponent(wishlistName);url+='&confidential='+wishlistConfidentiality;}else{url+=self.data('url-edit');url+='?wishlistId='+wishlistId;}
url+='&codics='+(config.codics||config.codic);url+='&note='+encodeURIComponent(note.val());if(typeof DARTY_CONF.CONST.SECURITY==="string"&&DARTY_CONF.CONST.SECURITY!==""){url+='&csrf_token='+DARTY_CONF.CONST.SECURITY;}
$.ajax({'type':'GET','url':url,'dataType':'json','success':function(data){DARTY_CONF.TRACKING.omniture_addProductToWishListConfirmation((''!=wishlistId)?wishlistId:'',wishlistName,config.codic);submit.prop('disabled',true);modal.find('.success').text("Ce produit a été ajouté à votre liste d'envies.");var s_darty=DARTY_CONF.TRACKING.getOmniture();DARTY_CONF.TRACKING.omniture_memorize(['pageName']);s_darty.pageName+="/envies/layer_confirmation_ajout";s_darty.prop24=wishlistId+"|"+wishlistName;s_darty.prop33="ajout_produit";s_darty.products=";"+config.codic+";;;event29;";DARTY_CONF.TRACKING.getSateliteOmniture().track("layerSimple");DARTY_CONF.TRACKING.omniture_reset();if(config.reload){location.reload();}else{setTimeout(function(){modal.trigger('closeModal');GLOBALE_FUN.refreshWishlistCount();},2500);}},'error':function(){modal.find('.error').text(GLOBALE_FUN.getErrorWishlist());DARTY_CONF.TRACKING.omniture_errorAddProductToWishlist("ERROR");}});});modal.trigger('openModal');}
$(document).ready(function(){$('#modal-add-product').easyModal({'onClose':function(modal){$(modal).find('[data-valid], #wishlist-new-name, #wishlist-select-name').off();}});$(document).on('click','[data-wishlist-add]',function(){var self=$(this);var config={'codic':self.data('codic'),'codics':self.data('codics'),'wishlist':self.data('wishlist-active'),'picture':self.data('picture'),'family':self.data('family'),'name':self.data('name'),'reload':self.data('wishlist-reload')};if(GLOBALE_FUN.userIsConnected()){modalAdd(config);}else{var url=window.location.pathname+window.location.search+'#openModal=add_product'
window.location=DARTY_CONF.CONST.DARTY_COM_SSL+'/espace_client/connexion?redirect='+encodeURIComponent(url);}});$(function(){var hash=document.location.hash.split('=');if('#openModal'==hash[0]&&'add_product'==hash[1]){$('[data-wishlist-add]').trigger('click');}});});
