
(function($){$(document).ready(function(){function animateTab(tab){var level1Links=tab.find('> a');var level2Links=tab.find('.level-2 > li > a');var timer1,timer2;var startTimer1=function(){timer1=setTimeout(function(){tab.find('a').removeClass('open');},20);};var startTimer2=function(item){timer2=setTimeout(function(){level2Links.removeClass('open');item.addClass('open');},20);};var clearTimer=function(timer){if(typeof timer!=="undefined"){clearTimeout(timer);}};function openMenu(item){clearTimer(timer1);if(item.parent().parent('.level-2').length){level2Links.removeClass('open');}
item.addClass('open');}
tab.on('focus','a',function(){openMenu($(this));});tab.on('blur','a',function(){startTimer1();});level1Links.on('mouseenter',function(){clearTimer(timer1);clearTimer(timer2);$(this).addClass('open');$(".fast-access").blur();});level2Links.on('mouseenter',function(){clearTimer(timer1);clearTimer(timer2);startTimer2($(this));});tab.on('mouseenter','.level-3',function(){clearTimer(timer1);clearTimer(timer2);});level1Links.add(level2Links).on('mouseleave',function(){startTimer1();});tab.on('mouseleave','.level-3',function(){startTimer1();});}
var mainTab=$('#main-tab');mainTab.find('.level-2 > li').css('width',mainTab.outerWidth(false));var secondaryTabs=$('li[id^=main-tab]');secondaryTabs.each(function(){animateTab($(this));});function injectSubMenus(data){var menus=$(data);menus.filter('ul').each(function(){$(this).appendTo(getParentMenu($(this).data('id')));});$('.level-3').css('left',mainTab.outerWidth(false));}
function getParentMenu(id){return mainTab.find('li[data-id="'+id+'"]');}
function loadCompleteMenu(){var url;var successCallback;url=DARTY_CONF.CONST.CTX_PATH+"nav/extra/ajax/headermenu_v3";if(!DARTY_CONF.CONST.DO_NOT_OPEN_XXL_SECTIONS){successCallback=injectSubMenus;}
var cacheXxl=true;if(typeof(DARTY_CONF.CONST.DEBUG_MENU)!=="undefined"&&DARTY_CONF.CONST.DEBUG_MENU){cacheXxl=false;}
if(typeof(DARTY_CONF.CONST.PREVIEW_USER)!=="undefined"&&DARTY_CONF.CONST.PREVIEW_USER!==""){url+="?preview_user="+DARTY_CONF.CONST.PREVIEW_USER;if(typeof(DARTY_CONF.CONST.PREVIEW_DATE)!=="undefined"&&DARTY_CONF.CONST.PREVIEW_DATE!==""){url+="&planning_date="+DARTY_CONF.CONST.PREVIEW_DATE;}
cacheXxl=false;}
if(DARTY_CONF.CONST.BYPASS_HEADER_CACHE){cacheXxl=false;}
$.ajax({'type':'GET','dataType':'html','url':url,'cache':cacheXxl,'success':successCallback});}
$(function(){if(typeof xxlheader_disable_ajax==="undefined"){loadCompleteMenu();}});});})(jQuery);

(function($){window.readCookies=function(){return{ck_displayname:getUserInfo(),bouser_info:getBOUserInfo(),order_info:getOrderInfo(),wishlist_info:getWishlistInfo(),has_basket_content:hasBasketContent()};function getUserInfo(){if(DARTY_CONF.userIsConnected()){return DARTY_CONF.getCookie('PCKFIRSTNAME');}
return null;}
function getOrderInfo(){var ck_orderInfos=DARTY_CONF.getCookie('PCKORDER');if(!ck_orderInfos){return{ck_order:null,ck_items:0,ck_amount:'0.00'};}
var orderInfos=ck_orderInfos.split('_');return{ck_order:orderInfos[0],ck_items:parseInt(orderInfos[1],10),ck_amount:orderInfos[2]};}
function getWishlistInfo(){var ck_wishlistInfos=DARTY_CONF.getCookie('PCKWISHLIST');if(!ck_wishlistInfos){return{ck_count:0};}
var wishlistInfos=ck_wishlistInfos.split('_');return{ck_count:wishlistInfos[0]};}
function getBOUserInfo(){var infos=DARTY_CONF.getCookie('CK_BO_USER');if(!infos){return null;}
var match=/^(.+)_([^_]+)$/.exec(infos);if(!match){return null;}
return{name:match[1],id:match[2]};}
function hasBasketContent(){var flag=0;if(getOrderInfo().ck_items>0){flag=1;}
return flag;}}
window.dartyComCallback=function(){if(typeof(callbackCatalogue)!=='undefined'){callbackCatalogue();}}
window.taggageOmniture=function(){$('#darty_header_espace_client').one("mouseover",function(){DARTY_CONF.TRACKING.omniture_openLoginHeader();});$("#darty_header_espace_client_login_popin a.creer").one('click',function(){DARTY_CONF.TRACKING.omniture_openLoginHeader("www","Inscription");});var parameters=(window.location.href.substring(window.location.href.indexOf('?')+1)).split('&');$.each(parameters,function(index,parameter){var paramSplit=parameter.split("=");var parameterName=paramSplit[0];var parameterValue=paramSplit[1];if(parameterName=='loginStatus'&&parameterValue=='badPassword'){DARTY_CONF.TRACKING.omniture_openLoginHeader("www","Saisie invalide");}});}
window.newsletterInit=function(){var button=$('#darty_header_newsletter_info_button');var popin=$('#darty_header_newsletter_info_popin');init();function init(){bindButton();};function bindButton(){if(button&&button.length>0&&popin&&popin.length>0){button.hover(function(){popin.show();},function(){popin.hide();});}};};})(jQuery);

var GLOBALE_FUN=GLOBALE_FUN||{};(function($){var userInit=function(userData,isDefaultDisplay){var displayer=$('#h_xxl_login');var lienMenu=$('#h_xxl_login_lien');var iconMenu=$('#user_icon');var labelIconMenu=$('#h_xxl_login_lien .label');var loggedinPopin=$('#h_xxl_login_loggedin_popin');var displayUserName=$('#h_xxl_login_loggedin_popin #h_xxl_login_username');update(userData);function update(userData){if(userData.bouser_info){bouser(userData);var initialUrl=$('#h_xxl_login_lien').attr('href');var newUrl=initialUrl+'&frontVendeur=1';$('#h_xxl_login_lien').attr('href',newUrl);if(DARTY_CONF.userIsConnected()&&$("#darty-back-office-client").length==0){var escapedDisplayName=escapeHtml(userData.ck_displayname);$("#darty-back-office-conseiller").after('<div class="title" id="darty-back-office-client">  |  Client : '+escapedDisplayName+'</div>');$('#darty-back-office-info div.content').after("<a class='darty-back-office-client-logout' href='"+DARTY_CONF.CONST.DARTY_COM_BASEURL+"/webapp/wcs/stores/servlet/UserLogoff?storeId=10001&org=logout&unsetClient=true'>D&eacute;connexion</a>")}
lienMenu.attr('src',DARTY_CONF.CONST.DARTY_COM_BASEURL+'/webapp/wcs/stores/controller/UserLogonDisplayView');lienMenu.attr('title','Espace Client');iconMenu.addClass('sprite_user_checked');labelIconMenu.html("Espace Client");lienMenu.show();}else{fouser(userData.ck_displayname);if(DARTY_CONF.TABLET&&userData.ck_displayname!==null){lienMenu.replaceWith("<div id='h_xxl_login_lien' class='h_xxl_login_lien'>"+lienMenu.html()+"</div>");}}};function fouser(firstName){if(isDefaultDisplay){if(firstName===null){labelIconMenu.html("Se connecter");lienMenu.attr('title',"Se connecter");}else{var nameHtmlEscaped=escapeHtml(firstName);labelIconMenu.html("CONNECT&Eacute;(E)");displayUserName.html("Bonjour "+nameHtmlEscaped);iconMenu.addClass('loggedIcon');lienMenu.removeAttr('title');DARTY_CONF.setStickyContainerEvents(displayer,loggedinPopin);}
lienMenu.show();DARTY_CONF.addPopinMask(displayer);}else{}};function bouser(userData){var boblock=$('#darty-back-office-info');var name=$('#darty-back-office-conseiller');var orderId=$('#darty-back-office-order');var userId=$('#darty-back-office-user-id');var topLink=$('#h_xxl_topLink');var boUserName=escapeHtml(userData.bouser_info.name);var boUserId=userData.bouser_info.id;var boOrderId=userData.order_info.ck_order;name.html(boUserName);userId.attr('value',boUserId);topLink.hide();boblock.show();};function escapeHtml(stringToEscape){return $("<div/>").text(stringToEscape).html();};};var wishlistInit=function(userData){var countSpan=$('#h_xxl_wishlist_count');if(DARTY_CONF.userIsConnected()){displayCount(userData);}
function displayCount(userData){var wishlistInfos=userData.wishlist_info;if(wishlistInfos!=null&&wishlistInfos.ck_count!=null&&wishlistInfos.ck_count>0&&countSpan.length!=0){countSpan.html(wishlistInfos.ck_count).removeClass('hide');}};};var basketInit=function(userData,executeReload){var countSpan=$("#h_xxl_panier_count");var updateBasket=function(){return function(userData){if(countSpan.length!=0){var ck_items=userData.order_info.ck_items;if(ck_items==null||ck_items==0){countSpan.hide();}
else{if(ck_items>9&&ck_items<100){countSpan.css('height','13px');countSpan.css('line-height','12px');}else if(ck_items>99){countSpan.css('top','-10px');countSpan.css('height','20px');countSpan.css('line-height','18px');}
countSpan.html(ck_items);countSpan.attr('data-basket-count',ck_items);countSpan.show();}}};}();updateBasket(userData);if(executeReload==undefined||executeReload){updateBasket(userData);}else{return function(){};}};GLOBALE_FUN.refreshWishlistCount=function(){var wishlist=Cookies.get('PCKWISHLIST');if(wishlist&&wishlist>0){var wishlistIndicator=$('#h_xxl_wishlist_count');wishlistIndicator.text(wishlist).removeClass('hide');}}
$(function(){var userData=readCookies();DARTY_CONF.reloadBasket=basketInit(userData);DARTY_CONF.reloadFacadeBasket=function(){basketInit(readCookies(),false);};userInit(userData,true);wishlistInit(userData);taggageOmniture();});})(jQuery);
