
DARTY_CONF.earlybirdsTracking=function(element){var href=element.attr('href');var codic=element.parents('.rr_item').data('codic')||element.parents('.product-card').data('codic');var widget=element.parents('[data-earlybirds]').data('earlybirds');var hooklogicURL=element.data('tracking-hook');if(href)event.preventDefault();if(hooklogicURL){$.ajax({'type':'GET','dataType':'html','url':hooklogicURL});}
window._ebq=window._ebq||[];window._ebq.push(['trackActivity',{'verb':'click-on-reco','original_id':codic,'widget':widget},function(){if(href)document.location=href;}]);};(function(w){$('body').on('refresh',function(){init();});function init(){var widgetsConfig={};var widgets=(function getWidgets(){var widgets=[];$.each($('[data-earlybirds]'),function(index,value){var widgetElt=$(value);var widgetId=widgetElt.data('earlybirds');widgetsConfig[widgetId]={'container':widgetElt,'isBanner':(widgetElt.data('earlybirds-banner'))?true:false,'ajaxUrl':(widgetElt.data('earlybirds-url'))?widgetElt.data('earlybirds-url'):'/nav/extra/ajax/earlybirds','isBasketPage':(widgetElt.data('earlybirds-isbasketpage'))?widgetElt.data('earlybirds-isbasketpage'):false,'univers':(widgetElt.data('earlybirds-univers'))?widgetElt.data('earlybirds-univers'):null,'side':(widgetElt.data('earlybirds-side'))?widgetElt.data('earlybirds-side'):null,'small':(widgetElt.data('earlybirds-small'))?true:false}
widgets.push(widgetId);});return widgets;})();function getWidgetsParams(array){return array.join('-');};function getProfileId(){var cookieEB=Cookies.get('eb-profile');return(cookieEB&&cookieEB.length)?cookieEB.split(':')[0]:'';};$('[data-earlybirds]').not('[data-earlybirds-banner]').on('click','a',function(event){DARTY_CONF.earlybirdsTracking($(this));});function loadWidget(ajaxData,widgetId,callback){$.ajax({'type':'POST','url':widgetsConfig[widgetId].ajaxUrl,'data':ajaxData,'success':function(data){if(!data.length)return;widgetsConfig[widgetId].container.html(data);if(typeof $('img').lazyload=='function'){$('#content').find('.js-lazyload').lazyload({'container':$('.body')});}
if(typeof DARTY_CONF.triggerCarousels=='function'){DARTY_CONF.triggerCarousels();}
if(typeof DARTY_CONF.triggerApercu=='function'){DARTY_CONF.triggerApercu();}
if(typeof DARTY_CONF.productCardLoadCallback=='function'){DARTY_CONF.productCardLoadCallback(widgetsConfig[widgetId].container);}
if(typeof DARTY_CONF.customCallback=='function'){DARTY_CONF.customCallback();}
if(callback)callback();}});};if(getWidgetsParams(widgets).length&&getProfileId().length){var ajaxData={'variables':{}};var codic=$('#main .page_product').data('codic')||$('body').data('codic');if(codic){ajaxData.variables.$productId=codic;}
var codic=$('.push-head').data('codic');if(codic){ajaxData.variables.$productId=codic;}
var category=$('#hierarchy_title').data('category');if(category&&category.length){ajaxData.variables.$category1=category;}
var productIds=[];$('#main_products_list .product_detail, #basket_content_inner_page tr[data-codic], #basket_content_inner_page .bundle_components[data-codic]').each(function(){var codic=$(this).data('codic');if(codic){productIds.push(codic);}});if(productIds&&productIds.length){ajaxData.variables.$productIds=productIds;}
var searchTerm=$('#request_title').data('search-term');if(searchTerm&&searchTerm.length){ajaxData.variables.$searchTerm=searchTerm;}
var universName=$('#carousel_title').data('univers-name');if(universName&&universName.length){ajaxData.variables.$universeName=universName;}
ajaxData.variables=JSON.stringify(ajaxData.variables);$.ajax({'type':'GET','url':'//api.early-birds.fr/widget/multi/'+getWidgetsParams(widgets)+'/recommendations/'+getProfileId(),'data':ajaxData,'success':function(data){$.each(widgets,function(index,widgetId){if(data[widgetId]&&data[widgetId].recommendations.length){var ajaxData={};var callback;if(widgetsConfig[widgetId].isBanner){ajaxData.imgurl=data[widgetId].recommendations[0].product.picture;ajaxData.mobileImgurl=data[widgetId].recommendations[0].product.pictureMobile;ajaxData.title=data[widgetId].recommendations[0].product.title;ajaxData.linkurl=data[widgetId].recommendations[0].product.url;ajaxData.univers=widgetsConfig[widgetId].univers;ajaxData.side=widgetsConfig[widgetId].side;callback=function(){var carouselHomeMobile=$('#carousel-home');if(carouselHomeMobile.length){carouselHomeMobile.trigger('destroy.owl.carousel').owlCarousel({'items':true,'lazyLoad':true,'navText':['','']});}
if(typeof DARTY_CONF.carouselImageProductOffset=='function'){DARTY_CONF.carouselImageProductOffset=1;}
if(typeof DARTY_CONF.triggerCarouselImageProduct=='function'){DARTY_CONF.triggerCarouselImageProduct();}
if(typeof DARTY_CONF.displayChezVousLe=='function'){DARTY_CONF.displayChezVousLe();}}}else{ajaxData.isBasketPage=widgetsConfig[widgetId].isBasketPage;ajaxData.titleMessage=data[widgetId].widget.title;ajaxData.minResults=data[widgetId].widget.minResults;ajaxData.items=JSON.stringify(data[widgetId].recommendations);ajaxData.rrSmall=widgetsConfig[widgetId].small;}
loadWidget(ajaxData,widgetId,callback);}});},'error':function(){}});}}
init();})(window);
